### ISSUE TITLE
I humbly beg forgiveness in advance, this is regarding Signal!

### ISSUE THREAD

**Issue by tbcx** [haffenloher/adaptiveHuffmanCompression#2]
This is *clearly* not how to contact you.  However, it occurred to me this might actually be a way to get in touch with you without being all kinds of spammy in the wrong kind of places.  Since you still had this repository online, and nobody seems to be paying it any kind of attention, I saw an opportunity and went for it!  Again, my apologies.

It's just that I noticed your version of Signal (which is the only one I use, grabbing it from your f-droid repo!) has gotten a version number bump that takes it ahead of the version number of the "official" WhisperSystems branch, to 3.29.1, as well as having grown substantially in size since the previous release, 3.26.2

I just felt a mild feeling of alarm at that, and though I should check with you whether your build 3.29.1 is indeed "legit" and not some insidious plant :-)

**Comment by haffenloher** [comment]
Hey, no worries. 3.29 is still in beta, it lives in the v3.29.0 branch upstream. The size growth is probably due to the new webrtc audio/video calls which you can enable in the advanced settings.

**Comment by tbcx** [comment]
Hello!  I wonder if replying to this email might work!  If so, I hope it
does without re-opening that "issue" on your HuffmanCompression thing!
Again, sorry to bother you like this, but I know of none other I can ask!
In fact, before anything else, might I trouble you for an actual email
address, so as not to go through GitHub?  (unless, of course, you'd prefer
we do, which is an elegant way of pretending you don't prefer I just plain
don't email you at all! :-) )

My question, then:  Is it better to use the microg gmscore from your repo,
or the one from the official microg F-droid repository?  I've got Signal
running beautifully, though running another app (the Android "Plex Home
Theater" client) seems constantly to crash the microG Services Framework
Proxy, so I wondered if a newer "Core" might alleviate that.

Assuming you reply me through some means;  thank you very much for taking
the time to reply!  And if I don't hear from you because you've just about
had enough of being pestered by strangers on the Internet, thanks very much
for all your work and putting together instructions so as to allow people
like me, who lack your knowledge and talent, to still run Signal without
having to use a personal Google account!

**Comment by haffenloher** [comment]
I set up my own repo simply because the official one didn't yet exist at the time. Which one you use shouldn't really matter as I just build from microg's master branch without changing anything.

There may still be good (security) reasons for using the official repo though, like timelier updates, and not installing software from some random stranger's web site. If you switch, I think you'll also need to switch to the FakeGapps version distributed through the Xposed installer, or else F-Droid might refuse to install / update microg stuff.

**Comment by tbcx** [comment]
Hello again!

Sorry AGAIN to be using this avenue to contact you, but, once again, I have
found no other means by which to get in touch.

Just wanted to ask, was it intentional that you deleted the content from
(what I assume to be) your website?  In particular, I often referred to
this link: https://o9i.de/2015/10/23/howto-gmscore.html  when setting up
new phones (for myself and others).

Regards,
Erlend

**Comment by haffenloher** [comment]
I didn't have the time to keep it updated and I also didn't feel the need for it, since in the meantime there's both an official repository and official, up-to-date installation instructions for microg stuff at https://microg.org/. People now use Yalp instead of Blank Store and self-updating Signal APKs are available at https://signal.org/android/apk/. Hope that helps!
